### ISSUE TITLE
Can't install 3.11-dev on macOS (`arm64`, `brew`, `2.3.0`)

### ISSUE THREAD

**Issue by Bobronium** [pyenv/pyenv#2377]
<details>
<summary>Prerequisite</summary>

Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.
</details>

Upon installing `3.11-dev` I'm getting

```
ERROR: invalid Python executable: /Users/bobronium/.pyenv/versions/3.11-dev/bin/python3.11

The python-build could not find proper executable of Python after successful build.
```

Seems very familiar to #1351, which apparently was only fixed by new hombrew release.

### Details
<details>
<summary>$ pyenv install 3.11-dev</summary>

```shell
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Cloning https://github.com/python/cpython...
Installing Python-3.11-dev...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
ERROR: invalid Python executable: /Users/bobronium/.pyenv/versions/3.11-dev/bin/python3.11

The python-build could not find proper executable of Python after successful build.
Please open an issue for future improvements.
https://github.com/pyenv/pyenv/issues

BUILD FAILED (OS X 12.4 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/sj/5p3z7pjd4qlb76z3d2vrjp3w0000gn/T/python-build.20220525005453.12412
Results logged to /var/folders/sj/5p3z7pjd4qlb76z3d2vrjp3w0000gn/T/python-build.20220525005453.12412.log

Last 10 log lines:
		 ./python.exe -E -m ensurepip \
			$ensurepip --root=/ ; \
	fi
Looking in links: /var/folders/sj/5p3z7pjd4qlb76z3d2vrjp3w0000gn/T/tmpybm_euww
Processing /private/var/folders/sj/5p3z7pjd4qlb76z3d2vrjp3w0000gn/T/tmpybm_euww/setuptools-58.1.0-py3-none-any.whl
Processing /private/var/folders/sj/5p3z7pjd4qlb76z3d2vrjp3w0000gn/T/tmpybm_euww/pip-22.0.4-py3-none-any.whl
Installing collected packages: setuptools, pip
  WARNING: The scripts pip3 and pip3.12 are installed in '/Users/bobronium/.pyenv/versions/3.11-dev/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-22.0.4 setuptools-58.1.0
```

</details>

### Description
- [x] Platform information:  macOS 12.4 (`21F79`)
- [x] OS architecture: `amd64`
- [x] pyenv version: `2.3.0` (from homebrew)
- [x] Python version: `3.11-dev`
- [x] C Compiler information: 
  ```
  Apple clang version 13.1.6 (clang-1316.0.21.2.5)
  Target: arm64-apple-darwin21.5.0
  Thread model: posix
  InstalledDir: /Library/Developer/CommandLineTools/usr/bin       
  ```

**Comment by native-api** [comment]
This has been fixed in https://github.com/pyenv/pyenv/pull/2361. Please upgrade to the head version (`brew install pyenv --head`).

The reason is that since the 2.3.0 release, the upstream switched the development head from 3.11 to 3.12.

**Comment by ssbarnea** [comment]
I had latest 2.3.2 and even tried head version and attempts to installed newer 3.11 fail getting stuck. I posted more details on https://github.com/pyenv/pyenv/discussions/2408 as I was not sure it was a bug in pyenv.

**Comment by ssbarnea** [comment]
Apparently that still happens, compilation works fine until it reaches:
```
renaming build/scripts-3.11/2to3 to build/scripts-3.11/2to3-3.11
```

After this nothing happens, is like it would be waiting for a prompt without displaying it. 

@native-api Any idea how to debug it? I already run with `-v`

**Comment by native-api** [comment]
@ssbarnea your issue is different. I wrote what to do.

**Comment by network-shark** [comment]
For me it is working fine . Do you have. 

export PATH="/opt/homebrew/opt/openssl@1.1/bin:$PATH" in your path ?

**Comment by ssbarnea** [comment]
@network-shark Yes, I did and same result. In fact I tested with `python-build 3.11-dev ~/py311-dev/` just to avoid having to touch my current working install

**Comment by network-shark** [comment]
@ssbarnea 
Your problem is that tkinter is missing. Maybe this helps 

https://xogk39.medium.com/install-tkinter-on-mac-pyenv-f112bd3f4663

**Comment by ssbarnea** [comment]
@network-shark This was not caused by tkinter missing, as that is acceptable use-case. It was caused by the fact that gnu/make was not installed and activated using `MAKE=gmake`. BSD make was causing this issue. Not sure if that would found as a pyenv issue as it seems more as a bug in python makefile itself. They should either fail fast with clear message or just fix it.
