### ISSUE TITLE
3.12.0 Build Failed Mac OS ARM 64 - ginstall: cannot stat 'Modules/_curses.cpython-312-darwin.so': No such file or directory

### ISSUE THREAD

**Issue by vacarme** [pyenv/pyenv#2808]
### Prerequisite
* [✅ ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [✅ ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [✅ ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ ✅] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [✅ ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [✅ ] Platform information (e.g. Ubuntu Linux 16.04): OS X 13.5.2
- [✅ ] OS architecture (e.g. amd64): arm64
- [ ✅] pyenv version: 2.3.28
- [ ✅] Python version: 3.12.0
- [ ✅] C Compiler information (e.g. gcc 7.3):  clang version 15.0.0 (clang-1500.0.40.1)
- [ ✅] Please attach the debug trace of the failing command as a gist:

Hello everybody,

I am sharing a potentially interesting issue trying to build python 3.12.0, here you can find the entire log file:
[pyenv-build.log](https://gist.github.com/vacarme/9a319494d4abdf88cf7fc27ffd9a0edd)

Command executed:

`env PYTHON_CONFIGURE_OPTS='--enable-optimizations --with-lto' PYTHON_CFLAGS='-march=native -mtune=native' pyenv install -v 3.12.0`

🔎 Potentially intesting line: 1070
```
./Modules/_cursesmodule.c:1338:9: warning: 'is_pad' is only available on macOS 14.0 or newer [-Wunguarded-availability-new]
```
  
I am not super experienced with the subject, so really sorry if I am waisting your time trying to fix a personal bug, this is really not my goal.

I am not in need of working with 3.12, so I am only here to raise the issue.

☮

**Comment by anton-petrov** [comment]
Duplicate of #2805

**Comment by vacarme** [comment]
sorry for that, I obviously checked this issue but mine do not seems to be related to openssl ?

**Comment by vacarme** [comment]
fixed
(probably by #2813)

**Comment by amicitas** [comment]
This problem still exists for me.  I use macports rather than homebrew, which may explain?

**Comment by native-api** [comment]
@amicitas Yes, Pyenv doesn't search for MacPorts atm. It needs to be used by passing compiler flags, like with other nonstandard setups.
Made a feature request: https://github.com/pyenv/pyenv/issues/3075
