### ISSUE TITLE
tkinter not working on pyenv install on macOS

### ISSUE THREAD

**Issue by exoriente** [pyenv/pyenv#3326]
# Tkinter is not working after pyenv install on macOS

I'm using pyenv on my MacBook and need to run an old project using `tkinter`. pyenv usually works flawlessly, but here I'm hitting a snag. I've tried various ways to do it as advised in blog and forum posts on the web and still can't make it work. It seems like it should work out of the box and is broken.

I've seen some other issues raised on `github.com/pyenv`, but they were closed due to lack of information from the reporter so I'll try to be as complete as I can.

#### Steps to reproduce and error message

```console
$ brew install tcl-tk
...
$ pyenv install 3.13.7
python-build: use openssl@3 from homebrew
python-build: use readline from homebrew
Installing Python-3.13.7...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use ncurses from homebrew
python-build: use zlib from xcode sdk
Installed Python-3.13.7 to /Users/user_id/.pyenv/versions/3.13.7
$ pyenv shell 3.13.7
$ python
Python 3.13.7 (main, Sep 11 2025, 10:09:25) [Clang 17.0.0 (clang-1700.0.13.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
$ >>> import tkinter
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import tkinter
  File "/Users/user_id/.pyenv/versions/3.13.7/lib/python3.13/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
```

#### Diagnostic details

- Platform: `macOS Sequoia 15.6.1 (24G90)`
- Architecture: `Apple M3 Pro`
- Pyenv version: `pyenv 2.6.7-13-g2ecd676a`
- Python version: `3.13.7`
- C Compiler information: `gcc --version`: 
  - `Apple clang version 17.0.0 (clang-1700.0.13.5)`
  - Target: `arm64-apple-darwin24.6.0`
  - Thread model: `posix`
  - InstalledDir: `/Library/Developer/CommandLineTools/usr/bin`
- `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`:
  - [trace.log](https://gist.github.com/exoriente/7c795bbdeae76b7dea896c2c7ac53378) as github gist

Let me know if more information is needed. I would be awesome to get this working!

**Comment by native-api** [comment]
Configure can't find Tcl/Tk for some reason even though we pass
```
++(/Users/klm10995/.pyenv/plugins/python-build/bin/python-build:1891): use_homebrew_tcltk(): export PKG_CONFIG_PATH=/opt/homebrew/opt/tcl-tk/lib/pkgconfig:/opt/homebrew/opt/openssl@3/lib/pkgconfig/:
```

please attach `config.log` as per the issue template

**Comment by exoriente** [comment]
Here you go. I hope this is the right file. I sniped it from some subdir in `/var`. Since the build process is successful it cleans up the build directory, it seems. Running `pyenv install -v` mentioned a folder in `var/` and I searched it for a ` config.log`. Here it is.

[config.log](https://github.com/user-attachments/files/22314442/config.log)

**Comment by exoriente** [comment]
I had a look at the `config.log` myself and saw some complaints about something related to X11 missing. I did `brew install libx11` to see if it would help. It does seem to eliminate the error, but `tkinter` still doesn't work.

Here's a the config.log of an installation by pyenv after `libx11` was installed using homebrew.

[config.log](https://github.com/user-attachments/files/22314494/config.log)

The result is still the same:

```console
$  python -c "import tkinter"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import tkinter
  File "/Users/klm10995/.pyenv/versions/3.13.7/lib/python3.13/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
```

**Comment by native-api** [comment]
> Since the build process is successful it cleans up the build directory, it seems.

When you build with `-k`, the build does not clear the build directory and it's under `$(pyenv root)/sources`

**Comment by exoriente** [comment]
Kewl. Here it is: 

[config.log](https://github.com/user-attachments/files/22315256/config.log)

**Comment by native-api** [comment]
> configure:3951: checking for pkg-config
> configure:3989: result: no

You don't have `pkg-config`. That's probably what changed. The error that you saw was from Configure trying to use Tck/Tk from XCode SDK which is deprecated and broken.

Previously, CPython accepted `--with-tcltk-*` configure options but [they changed it since 3.11.0](https://github.com/python/cpython/commit/b36d222110d0d6d84dc8e973ca87d976c2423f5d) to a `pkg-config` call with `TCLTK_CFLAGS` and `TCLTK_LIBS` envvars as overrides. We set the path for `pkg-config` but don't set the overrides if it's missing.

So you can either `brew install pkg-config`, or set those envvars as a workaround:
```
export TCLTK_CFLAGS="-I$(brew --prefix tcl-tk@8)/include/tcl-tk"
export TCLTK_LIBS="-L$(brew --prefix tcl-tk@8)/lib -ltcl8.6 -ltk8.6"
```

**Comment by exoriente** [comment]
I tried both fixes.

- `brew install pkg-config` ✅ 
  - Works perfectly! Thanks for this. My problem is solved.
- Setting the envvars ❌ 
  - I tried this too, for completeness' sake. Setting the envvars did not make a difference. Still got the same `_tkinter` error.

Regardless, my problem is solved. Installing `pkg-config` is the more convenient solution anyway and has no downsides in my case. I've added `pkg-config` here:

- https://github.com/pyenv/pyenv/wiki#suggested-build-environment

It might help others that run into the same problem. The package was already included in the MacPorts line anyway.

Thanks for the help!

**Comment by WurmD** [comment]
```
25-10-09 12:23:28 ➜  ~ brew install tcl-tk pkg-config
Warning: tcl-tk 9.0.2 is already installed and up-to-date.
To reinstall 9.0.2, run:
  brew reinstall tcl-tk
Warning: pkgconf 2.5.1 is already installed and up-to-date.
To reinstall 2.5.1, run:
  brew reinstall pkgconf

25-10-09 12:23:52 ➜  ~ pyenv install 3.12.11
pyenv: /Users/dario.figueira/.pyenv/versions/3.12.11 already exists
continue with installation? (y/N)

25-10-09 12:24:33 ➜  ~ pyenv shell 3.12.11

25-10-09 12:24:39 ➜  ~ python -c "import tkinter"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dario.figueira/.pyenv/versions/3.12.11/lib/python3.12/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
```

I still have the snag :/ 

(Should I create a new issue?)

#### Diagnostic details
- Platform information:  Mac OS 15.6.1 (24G90)
- OS architecture: Apple M1 Max
- pyenv version: 2.6.9
- Python version: 3.12.11
- C Compiler information: gcc --version
Apple clang version 17.0.0 (clang-1700.3.19.1)
Target: arm64-apple-darwin24.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
- [ ] Please attach the debug trace of the failing command as a [gist](https://gist.github.com/): what command should I give the tracelog?

**Comment by native-api** [comment]
> brew install tcl-tk pkg-config
> Warning: tcl-tk 9.0.2 is already installed and up-to-date.

https://github.com/pyenv/pyenv/pull/3343

**Comment by WurmD** [comment]
```
25-10-09 12:47:32 ➜  ~ brew list tcl-tk
Error: No such keg: /opt/homebrew/Cellar/tcl-tk

25-10-09 12:47:40 ➜  ~ brew install tcl-tk@8 pkg-config
Warning: tcl-tk@8 8.6.17 is already installed and up-to-date.
To reinstall 8.6.17, run:
  brew reinstall tcl-tk@8
Warning: pkgconf 2.5.1 is already installed and up-to-date.
To reinstall 2.5.1, run:
  brew reinstall pkgconf

25-10-09 12:47:45 ➜  ~ pyenv install 3.12.11
python-build: use openssl@3 from homebrew
python-build: use readline from homebrew
Downloading Python-3.12.11.tar.xz...
-> https://www.python.org/ftp/python/3.12.11/Python-3.12.11.tar.xz
Installing Python-3.12.11...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use ncurses from homebrew
python-build: use zlib from xcode sdk
Installed Python-3.12.11 to /Users/dario.figueira/.pyenv/versions/3.12.11

25-10-09 12:50:30 ➜  ~ pyenv shell 3.12.11

25-10-09 12:50:43 ➜  ~ python -c "import tkinter"

25-10-09 12:50:48 ➜  ~
```
SUCCESS!
