### ISSUE TITLE
shims do not work with gettext (.pyenv/shims/gettext.sh)

### ISSUE THREAD

**Issue by cpaulik** [pyenv/pyenv#688]
The `git submodule` command hangs producing the following output:

``` shell
❯ git submodule
/usr/lib/git-core/git-submodule: 6: /home/cpa/.pyenv/shims/gettext.sh: [[: not found
/usr/lib/git-core/git-submodule: 6: /home/cpa/.pyenv/shims/gettext.sh: [[: not found
/usr/lib/git-core/git-submodule: 6: /home/cpa/.pyenv/shims/gettext.sh: [[: not found
/usr/lib/git-core/git-submodule: 6: /home/cpa/.pyenv/shims/gettext.sh: [[: not found
.
.
.
```

This happens in any git directory regardless of it having submodules or not.

``` shell
❯ git --version
git version 2.9.3
```
##

**Comment by cpaulik** [comment]
This is cause by installing e.g. https://anaconda.org/conda-forge/gettext into one of the environments. After testing a little bit more I noticed that this breaks a lot of other git commands.

**Comment by sebhahn** [comment]
I can confirm this problem!

**Comment by JunsikChoi** [comment]
I got the same problem. Solved by remove gettext

**Comment by sebhahn** [comment]
Any chance that this problem can be fixed?

**Comment by yyuu** [comment]
The actual _problem_ is in git-core. It seems it's trying to search `gettext.sh` from `$PATH` then `source` it.

https://github.com/git/git/blob/v2.13.3/git-sh-i18n.sh#L46

As a tentative workaround, setting something in `GIT_INTERNAL_GETTEXT_TEST_FALLBACKS` might work.

```
export GIT_INTERNAL_GETTEXT_TEST_FALLBACKS=1
```

**Comment by sebhahn** [comment]
Thanks, I'll test it.

**Comment by cpaulik** [comment]
I'm using these cronjobs as a workaround.

```
* * * * * rm /home/cpa/.pyenv/shims/gettext
* * * * * rm /home/cpa/.pyenv/shims/gettext.sh
```

Ugly but it works.

**Comment by yyuu** [comment]
I've merged #953 into master. By that changes, the shim script for `gettext.sh` will be generated as source'able script. Just regenerating shims by hitting `pyenv rehash`.

**Comment by zarzen** [comment]
similar problem, tried method proposed here, but problem still exists. system info: ubuntu 18.04
following is the debug output. (I have updated pyenv, with `git pull` under `~/.pyenv` folder)
```
 git submodule 
+ export PYENV_ROOT=/home/zarzen/.pyenv
+ /home/zarzen/.pyenv/libexec/pyenv which 
+ [pyenv:22] enable -f /home/zarzen/.pyenv/libexec/../libexec/pyenv-realpath.dylib realpath
+ [pyenv:29] '[' -z '' ']'
++ [pyenv:31] type -p greadlink readlink
++ [pyenv:31] head -1
+ [pyenv:31] READLINK=/bin/readlink
+ [pyenv:32] '[' -n /bin/readlink ']'
+ [pyenv:54] '[' -z /home/zarzen/.pyenv ']'
+ [pyenv:57] PYENV_ROOT=/home/zarzen/.pyenv
+ [pyenv:59] export PYENV_ROOT
+ [pyenv:62] '[' -z '' ']'
+ [pyenv:63] '[' -n '' ']'
+ [pyenv:79] '[' -z '' ']'
+ [pyenv:80] PYENV_DIR=/home/zarzen/Dev/data_annotation
+ [pyenv:83] '[' '!' -d /home/zarzen/Dev/data_annotation ']'
+ [pyenv:83] '[' '!' -e /home/zarzen/Dev/data_annotation ']'
++ [pyenv:87] cd /home/zarzen/Dev/data_annotation
++ [pyenv:87] echo /home/zarzen/Dev/data_annotation
+ [pyenv:87] PYENV_DIR=/home/zarzen/Dev/data_annotation
+ [pyenv:88] export PYENV_DIR
+ [pyenv:91] shopt -s nullglob
++ [pyenv:93] abs_dirname /home/zarzen/.pyenv/libexec/pyenv
++ [pyenv:39] local path=/home/zarzen/.pyenv/libexec/pyenv
++ [pyenv:43] '[' -n /home/zarzen/.pyenv/libexec/pyenv ']'
++ [pyenv:44] cd /home/zarzen/.pyenv/libexec
++ [pyenv:45] local name=pyenv
+++ [pyenv:46] resolve_link pyenv
+++ [pyenv:35] /bin/readlink pyenv
+++ [pyenv:46] true
++ [pyenv:46] path=
++ [pyenv:43] '[' -n '' ']'
++ [pyenv:49] pwd
+ [pyenv:93] bin_path=/home/zarzen/.pyenv/libexec
+ [pyenv:94] for plugin_bin in "${PYENV_ROOT}/plugins/"*/bin
+ [pyenv:95] PATH=/home/zarzen/.pyenv/plugins/pyenv-doctor/bin:/usr/lib/git-core:/home/zarzen/.opam/4.07.0/bin:/home/zarzen/perl5/bin:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/shims:/home/zarzen/.pyenv/shims:/home/zarzen/.pyenv/bin:/usr/local/cuda-9.0/bin:/home/zarzen/.local/bin:/home/zarzen/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/zarzen/go/bin:/home/zarzen/platform-tools
+ [pyenv:94] for plugin_bin in "${PYENV_ROOT}/plugins/"*/bin
+ [pyenv:95] PATH=/home/zarzen/.pyenv/plugins/pyenv-installer/bin:/home/zarzen/.pyenv/plugins/pyenv-doctor/bin:/usr/lib/git-core:/home/zarzen/.opam/4.07.0/bin:/home/zarzen/perl5/bin:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/shims:/home/zarzen/.pyenv/shims:/home/zarzen/.pyenv/bin:/usr/local/cuda-9.0/bin:/home/zarzen/.local/bin:/home/zarzen/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/zarzen/go/bin:/home/zarzen/platform-tools
+ [pyenv:94] for plugin_bin in "${PYENV_ROOT}/plugins/"*/bin
+ [pyenv:95] PATH=/home/zarzen/.pyenv/plugins/pyenv-update/bin:/home/zarzen/.pyenv/plugins/pyenv-installer/bin:/home/zarzen/.pyenv/plugins/pyenv-doctor/bin:/usr/lib/git-core:/home/zarzen/.opam/4.07.0/bin:/home/zarzen/perl5/bin:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/shims:/home/zarzen/.pyenv/shims:/home/zarzen/.pyenv/bin:/usr/local/cuda-9.0/bin:/home/zarzen/.local/bin:/home/zarzen/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/zarzen/go/bin:/home/zarzen/platform-tools
+ [pyenv:94] for plugin_bin in "${PYENV_ROOT}/plugins/"*/bin
+ [pyenv:95] PATH=/home/zarzen/.pyenv/plugins/pyenv-virtualenv/bin:/home/zarzen/.pyenv/plugins/pyenv-update/bin:/home/zarzen/.pyenv/plugins/pyenv-installer/bin:/home/zarzen/.pyenv/plugins/pyenv-doctor/bin:/usr/lib/git-core:/home/zarzen/.opam/4.07.0/bin:/home/zarzen/perl5/bin:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/shims:/home/zarzen/.pyenv/shims:/home/zarzen/.pyenv/bin:/usr/local/cuda-9.0/bin:/home/zarzen/.local/bin:/home/zarzen/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/zarzen/go/bin:/home/zarzen/platform-tools
+ [pyenv:94] for plugin_bin in "${PYENV_ROOT}/plugins/"*/bin
+ [pyenv:95] PATH=/home/zarzen/.pyenv/plugins/python-build/bin:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/bin:/home/zarzen/.pyenv/plugins/pyenv-update/bin:/home/zarzen/.pyenv/plugins/pyenv-installer/bin:/home/zarzen/.pyenv/plugins/pyenv-doctor/bin:/usr/lib/git-core:/home/zarzen/.opam/4.07.0/bin:/home/zarzen/perl5/bin:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/shims:/home/zarzen/.pyenv/shims:/home/zarzen/.pyenv/bin:/usr/local/cuda-9.0/bin:/home/zarzen/.local/bin:/home/zarzen/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/zarzen/go/bin:/home/zarzen/platform-tools
+ [pyenv:97] export PATH=/home/zarzen/.pyenv/libexec:/home/zarzen/.pyenv/plugins/python-build/bin:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/bin:/home/zarzen/.pyenv/plugins/pyenv-update/bin:/home/zarzen/.pyenv/plugins/pyenv-installer/bin:/home/zarzen/.pyenv/plugins/pyenv-doctor/bin:/usr/lib/git-core:/home/zarzen/.opam/4.07.0/bin:/home/zarzen/perl5/bin:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/shims:/home/zarzen/.pyenv/shims:/home/zarzen/.pyenv/bin:/usr/local/cuda-9.0/bin:/home/zarzen/.local/bin:/home/zarzen/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/zarzen/go/bin:/home/zarzen/platform-tools
+ [pyenv:97] PATH=/home/zarzen/.pyenv/libexec:/home/zarzen/.pyenv/plugins/python-build/bin:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/bin:/home/zarzen/.pyenv/plugins/pyenv-update/bin:/home/zarzen/.pyenv/plugins/pyenv-installer/bin:/home/zarzen/.pyenv/plugins/pyenv-doctor/bin:/usr/lib/git-core:/home/zarzen/.opam/4.07.0/bin:/home/zarzen/perl5/bin:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/shims:/home/zarzen/.pyenv/shims:/home/zarzen/.pyenv/bin:/usr/local/cuda-9.0/bin:/home/zarzen/.local/bin:/home/zarzen/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/zarzen/go/bin:/home/zarzen/platform-tools
+ [pyenv:99] PYENV_HOOK_PATH=:/home/zarzen/.pyenv/pyenv.d
+ [pyenv:100] '[' /home/zarzen/.pyenv '!=' /home/zarzen/.pyenv ']'
+ [pyenv:104] PYENV_HOOK_PATH=:/home/zarzen/.pyenv/pyenv.d:/usr/local/etc/pyenv.d:/etc/pyenv.d:/usr/lib/pyenv/hooks
+ [pyenv:105] for plugin_hook in "${PYENV_ROOT}/plugins/"*/etc/pyenv.d
+ [pyenv:106] PYENV_HOOK_PATH=:/home/zarzen/.pyenv/pyenv.d:/usr/local/etc/pyenv.d:/etc/pyenv.d:/usr/lib/pyenv/hooks:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/etc/pyenv.d
+ [pyenv:105] for plugin_hook in "${PYENV_ROOT}/plugins/"*/etc/pyenv.d
+ [pyenv:106] PYENV_HOOK_PATH=:/home/zarzen/.pyenv/pyenv.d:/usr/local/etc/pyenv.d:/etc/pyenv.d:/usr/lib/pyenv/hooks:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/etc/pyenv.d:/home/zarzen/.pyenv/plugins/pyenv-which-ext/etc/pyenv.d
+ [pyenv:108] PYENV_HOOK_PATH=/home/zarzen/.pyenv/pyenv.d:/usr/local/etc/pyenv.d:/etc/pyenv.d:/usr/lib/pyenv/hooks:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/etc/pyenv.d:/home/zarzen/.pyenv/plugins/pyenv-which-ext/etc/pyenv.d
+ [pyenv:109] export PYENV_HOOK_PATH
+ [pyenv:111] shopt -u nullglob
+ [pyenv:114] command=which
+ [pyenv:115] case "$command" in
++ [pyenv:128] command -v pyenv-which
+ [pyenv:128] command_path=/home/zarzen/.pyenv/libexec/pyenv-which
+ [pyenv:129] '[' -z /home/zarzen/.pyenv/libexec/pyenv-which ']'
+ [pyenv:137] shift 1
+ [pyenv:138] '[' '' = --help ']'
+ [pyenv:145] exec /home/zarzen/.pyenv/libexec/pyenv-which ''
+ [pyenv-which:14] '[' '' = --complete ']'
+ [pyenv-which:30] PYENV_COMMAND=
+ [pyenv-which:32] '[' -z '' ']'
+ [pyenv-which:33] pyenv-help --usage which
+ [pyenv-help:19] '[' --usage = --complete ']'
+ [pyenv-help:143] unset usage
+ [pyenv-help:144] '[' --usage = --usage ']'
+ [pyenv-help:145] usage=1
+ [pyenv-help:146] shift
+ [pyenv-help:149] '[' -z which ']'
+ [pyenv-help:149] '[' which == pyenv ']'
+ [pyenv-help:159] command=which
++ [pyenv-help:160] command_path which
++ [pyenv-help:25] local command=which
++ [pyenv-help:26] command -v pyenv-which
+ [pyenv-help:160] '[' -n /home/zarzen/.pyenv/libexec/pyenv-which ']'
+ [pyenv-help:161] '[' -n 1 ']'
+ [pyenv-help:162] print_usage which
+ [pyenv-help:137] local command=which
+ [pyenv-help:138] local summary usage help
++ [pyenv-help:139] documentation_for which
++ [pyenv-help:90] local filename
+++ [pyenv-help:91] command_path which
+++ [pyenv-help:25] local command=which
+++ [pyenv-help:26] command -v pyenv-which
++ [pyenv-help:91] filename=/home/zarzen/.pyenv/libexec/pyenv-which
++ [pyenv-help:92] '[' -n /home/zarzen/.pyenv/libexec/pyenv-which ']'
++ [pyenv-help:93] extract_initial_comment_block
++ [pyenv-help:30] sed -ne '
    /^#/ !{
      q
    }

    s/^#$/# /

    /^# / {
      s/^# //
      p
    }
  '
++ [pyenv-help:93] collect_documentation
+++ [pyenv-help:86] type -p gawk awk
+++ [pyenv-help:86] head -1
++ [pyenv-help:86] /usr/bin/awk '
    /^Summary:/ {
      summary = substr($0, 10)
      next
    }

    /^Usage:/ {
      reading_usage = 1
      usage = usage "\n" $0
      next
    }

    /^( *$|       )/ && reading_usage {
      usage = usage "\n" $0
      next
    }

    {
      reading_usage = 0
      help = help "\n" $0
    }

    function escape(str) {
      gsub(/[`\\$"]/, "\\\\&", str)
      return str
    }

    function trim(str) {
      sub(/^\n*/, "", str)
      sub(/\n*$/, "", str)
      return str
    }

    END {
      if (usage || summary) {
        print "summary=\"" escape(summary) "\""
        print "usage=\"" escape(trim(usage)) "\""
        print "help=\"" escape(trim(help)) "\""
      }
    }
  '
+ [pyenv-help:139] eval 'summary="Display the full path to an executable"
usage="Usage: pyenv which <command>"
help="Displays the full path to the executable that pyenv will invoke when
you run the given command."'
++ [pyenv-help:139] summary='Display the full path to an executable'
++ [pyenv-help:140] usage='Usage: pyenv which <command>'
++ [pyenv-help:142] help='Displays the full path to the executable that pyenv will invoke when
you run the given command.'
+ [pyenv-help:140] '[' -z 'Usage: pyenv which <command>' ']'
+ [pyenv-help:140] echo 'Usage: pyenv which <command>'
Usage: pyenv which <command>
+ [pyenv-which:34] exit 1
+ program=
+ [ -e  ]
+ GIT_QUIET=
+ test -n 
+ basename -- /usr/lib/git-core/git-submodule
+ sed -e s/-/ /
+ dashless=git submodule
+ [ -z  ]
+ eval_gettext usage: $dashless $USAGE
/usr/lib/git-core/git-submodule: 93: /usr/lib/git-core/git-sh-setup: eval_gettext: not found
+ LONG_USAGE=
+ uname -s
+ test -z 
+ git_dir_init
+ git rev-parse --git-dir
+ GIT_DIR=.git
+ [ -z Yes ]
+ test -n .git
+ cd .git
+ pwd
+ GIT_DIR=/home/zarzen/Dev/data_annotation/.git
+ git rev-parse --git-path objects
+ : .git/objects
+ . git-parse-remote
+ git rev-parse -q --git-dir
+ GIT_DIR=.git
+ require_work_tree
+ git rev-parse --is-inside-work-tree
+ test true = true
+ git rev-parse --show-prefix
+ wt_prefix=
+ cd_to_toplevel
+ git rev-parse --show-toplevel
+ cdup=/home/zarzen/Dev/data_annotation
+ cd /home/zarzen/Dev/data_annotation
+ GIT_PROTOCOL_FROM_USER=0
+ export GIT_PROTOCOL_FROM_USER
+ command=
+ branch=
+ force=
+ reference=
+ cached=
+ recursive=
+ init=
+ files=
+ remote=
+ nofetch=
+ update=
+ prefix=
+ custom_name=
+ depth=
+ progress=
+ test 0 != 0
+ test -z 
+ test 0 = 0
+ command=status
+ test -n 
+ test -n 
+ cmd_status
+ test 0 -ne 0
+ git submodule--helper status
+ [pyenv:22] enable -f /home/zarzen/.pyenv/bin/../libexec/pyenv-realpath.dylib realpath                                                                                                                            
+ [pyenv:29] '[' -z '' ']'
++ [pyenv:31] type -p greadlink readlink
++ [pyenv:31] head -1
+ [pyenv:31] READLINK=/bin/readlink
+ [pyenv:32] '[' -n /bin/readlink ']'
+ [pyenv:54] '[' -z /home/zarzen/.pyenv ']'
+ [pyenv:57] PYENV_ROOT=/home/zarzen/.pyenv
+ [pyenv:59] export PYENV_ROOT
+ [pyenv:62] '[' -z '' ']'
+ [pyenv:63] '[' -n '' ']'
+ [pyenv:79] '[' -z '' ']'
+ [pyenv:80] PYENV_DIR=/home/zarzen/Dev/data_annotation
+ [pyenv:83] '[' '!' -d /home/zarzen/Dev/data_annotation ']'
+ [pyenv:83] '[' '!' -e /home/zarzen/Dev/data_annotation ']'
++ [pyenv:87] cd /home/zarzen/Dev/data_annotation
++ [pyenv:87] echo /home/zarzen/Dev/data_annotation
+ [pyenv:87] PYENV_DIR=/home/zarzen/Dev/data_annotation
+ [pyenv:88] export PYENV_DIR
+ [pyenv:91] shopt -s nullglob
++ [pyenv:93] abs_dirname /home/zarzen/.pyenv/bin/pyenv
++ [pyenv:39] local path=/home/zarzen/.pyenv/bin/pyenv
++ [pyenv:43] '[' -n /home/zarzen/.pyenv/bin/pyenv ']'
++ [pyenv:44] cd /home/zarzen/.pyenv/bin
++ [pyenv:45] local name=pyenv
+++ [pyenv:46] resolve_link pyenv
+++ [pyenv:35] /bin/readlink pyenv
++ [pyenv:46] path=../libexec/pyenv
++ [pyenv:43] '[' -n ../libexec/pyenv ']'
++ [pyenv:44] cd ../libexec
++ [pyenv:45] local name=pyenv
+++ [pyenv:46] resolve_link pyenv
+++ [pyenv:35] /bin/readlink pyenv
+++ [pyenv:46] true
++ [pyenv:46] path=
++ [pyenv:43] '[' -n '' ']'
++ [pyenv:49] pwd
+ [pyenv:93] bin_path=/home/zarzen/.pyenv/libexec
+ [pyenv:94] for plugin_bin in "${PYENV_ROOT}/plugins/"*/bin
+ [pyenv:95] PATH=/home/zarzen/.pyenv/plugins/pyenv-doctor/bin:/home/zarzen/.opam/4.07.0/bin:/home/zarzen/perl5/bin:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/shims:/home/zarzen/.pyenv/shims:/home/zarzen/.pyenv/bin:/usr/local/cuda-9.0/bin:/home/zarzen/.local/bin:/home/zarzen/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/zarzen/go/bin:/home/zarzen/platform-tools
+ [pyenv:94] for plugin_bin in "${PYENV_ROOT}/plugins/"*/bin
+ [pyenv:95] PATH=/home/zarzen/.pyenv/plugins/pyenv-installer/bin:/home/zarzen/.pyenv/plugins/pyenv-doctor/bin:/home/zarzen/.opam/4.07.0/bin:/home/zarzen/perl5/bin:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/shims:/home/zarzen/.pyenv/shims:/home/zarzen/.pyenv/bin:/usr/local/cuda-9.0/bin:/home/zarzen/.local/bin:/home/zarzen/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/zarzen/go/bin:/home/zarzen/platform-tools
+ [pyenv:94] for plugin_bin in "${PYENV_ROOT}/plugins/"*/bin
+ [pyenv:95] PATH=/home/zarzen/.pyenv/plugins/pyenv-update/bin:/home/zarzen/.pyenv/plugins/pyenv-installer/bin:/home/zarzen/.pyenv/plugins/pyenv-doctor/bin:/home/zarzen/.opam/4.07.0/bin:/home/zarzen/perl5/bin:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/shims:/home/zarzen/.pyenv/shims:/home/zarzen/.pyenv/bin:/usr/local/cuda-9.0/bin:/home/zarzen/.local/bin:/home/zarzen/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/zarzen/go/bin:/home/zarzen/platform-tools
+ [pyenv:94] for plugin_bin in "${PYENV_ROOT}/plugins/"*/bin
+ [pyenv:95] PATH=/home/zarzen/.pyenv/plugins/pyenv-virtualenv/bin:/home/zarzen/.pyenv/plugins/pyenv-update/bin:/home/zarzen/.pyenv/plugins/pyenv-installer/bin:/home/zarzen/.pyenv/plugins/pyenv-doctor/bin:/home/zarzen/.opam/4.07.0/bin:/home/zarzen/perl5/bin:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/shims:/home/zarzen/.pyenv/shims:/home/zarzen/.pyenv/bin:/usr/local/cuda-9.0/bin:/home/zarzen/.local/bin:/home/zarzen/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/zarzen/go/bin:/home/zarzen/platform-tools
+ [pyenv:94] for plugin_bin in "${PYENV_ROOT}/plugins/"*/bin
+ [pyenv:95] PATH=/home/zarzen/.pyenv/plugins/python-build/bin:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/bin:/home/zarzen/.pyenv/plugins/pyenv-update/bin:/home/zarzen/.pyenv/plugins/pyenv-installer/bin:/home/zarzen/.pyenv/plugins/pyenv-doctor/bin:/home/zarzen/.opam/4.07.0/bin:/home/zarzen/perl5/bin:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/shims:/home/zarzen/.pyenv/shims:/home/zarzen/.pyenv/bin:/usr/local/cuda-9.0/bin:/home/zarzen/.local/bin:/home/zarzen/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/zarzen/go/bin:/home/zarzen/platform-tools
+ [pyenv:97] export PATH=/home/zarzen/.pyenv/libexec:/home/zarzen/.pyenv/plugins/python-build/bin:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/bin:/home/zarzen/.pyenv/plugins/pyenv-update/bin:/home/zarzen/.pyenv/plugins/pyenv-installer/bin:/home/zarzen/.pyenv/plugins/pyenv-doctor/bin:/home/zarzen/.opam/4.07.0/bin:/home/zarzen/perl5/bin:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/shims:/home/zarzen/.pyenv/shims:/home/zarzen/.pyenv/bin:/usr/local/cuda-9.0/bin:/home/zarzen/.local/bin:/home/zarzen/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/zarzen/go/bin:/home/zarzen/platform-tools
+ [pyenv:97] PATH=/home/zarzen/.pyenv/libexec:/home/zarzen/.pyenv/plugins/python-build/bin:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/bin:/home/zarzen/.pyenv/plugins/pyenv-update/bin:/home/zarzen/.pyenv/plugins/pyenv-installer/bin:/home/zarzen/.pyenv/plugins/pyenv-doctor/bin:/home/zarzen/.opam/4.07.0/bin:/home/zarzen/perl5/bin:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/shims:/home/zarzen/.pyenv/shims:/home/zarzen/.pyenv/bin:/usr/local/cuda-9.0/bin:/home/zarzen/.local/bin:/home/zarzen/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/zarzen/go/bin:/home/zarzen/platform-tools
+ [pyenv:99] PYENV_HOOK_PATH=:/home/zarzen/.pyenv/pyenv.d
+ [pyenv:100] '[' /home/zarzen/.pyenv '!=' /home/zarzen/.pyenv ']'
+ [pyenv:104] PYENV_HOOK_PATH=:/home/zarzen/.pyenv/pyenv.d:/usr/local/etc/pyenv.d:/etc/pyenv.d:/usr/lib/pyenv/hooks
+ [pyenv:105] for plugin_hook in "${PYENV_ROOT}/plugins/"*/etc/pyenv.d
+ [pyenv:106] PYENV_HOOK_PATH=:/home/zarzen/.pyenv/pyenv.d:/usr/local/etc/pyenv.d:/etc/pyenv.d:/usr/lib/pyenv/hooks:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/etc/pyenv.d
+ [pyenv:105] for plugin_hook in "${PYENV_ROOT}/plugins/"*/etc/pyenv.d
+ [pyenv:106] PYENV_HOOK_PATH=:/home/zarzen/.pyenv/pyenv.d:/usr/local/etc/pyenv.d:/etc/pyenv.d:/usr/lib/pyenv/hooks:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/etc/pyenv.d:/home/zarzen/.pyenv/plugins/pyenv-which-ext/etc/pyenv.d
+ [pyenv:108] PYENV_HOOK_PATH=/home/zarzen/.pyenv/pyenv.d:/usr/local/etc/pyenv.d:/etc/pyenv.d:/usr/lib/pyenv/hooks:/home/zarzen/.pyenv/plugins/pyenv-virtualenv/etc/pyenv.d:/home/zarzen/.pyenv/plugins/pyenv-which-ext/etc/pyenv.d
+ [pyenv:109] export PYENV_HOOK_PATH
+ [pyenv:111] shopt -u nullglob
+ [pyenv:114] command=sh-activate
+ [pyenv:115] case "$command" in
++ [pyenv:128] command -v pyenv-sh-activate
+ [pyenv:128] command_path=/home/zarzen/.pyenv/plugins/pyenv-virtualenv/bin/pyenv-sh-activate
+ [pyenv:129] '[' -z /home/zarzen/.pyenv/plugins/pyenv-virtualenv/bin/pyenv-sh-activate ']'
+ [pyenv:137] shift 1
+ [pyenv:138] '[' --quiet = --help ']'
+ [pyenv:145] exec /home/zarzen/.pyenv/plugins/pyenv-virtualenv/bin/pyenv-sh-activate --quiet
+ [pyenv-sh-activate:17] '[' -z /home/zarzen/.pyenv ']'
+ [pyenv-sh-activate:25] unset FORCE
+ [pyenv-sh-activate:26] unset QUIET
+ [pyenv-sh-activate:28] '[' 1 -gt 0 ']'
+ [pyenv-sh-activate:29] case "$1" in
+ [pyenv-sh-activate:39] QUIET=1
+ [pyenv-sh-activate:52] shift 1
+ [pyenv-sh-activate:28] '[' 0 -gt 0 ']'
+ [pyenv-sh-activate:55] no_shell=
+ [pyenv-sh-activate:56] versions=("$@")
+ [pyenv-sh-activate:57] '[' -z '' ']'
+ [pyenv-sh-activate:58] no_shell=1
+ [pyenv-sh-activate:59] OLDIFS=' 	
'
+ [pyenv-sh-activate:60] IFS=:
+ [pyenv-sh-activate:60] versions=($(pyenv-version-name 2>/dev/null))
++ [pyenv-sh-activate:60] pyenv-version-name
+ [pyenv-sh-activate:61] IFS=' 	
'
+ [pyenv-sh-activate:64] '[' -z 1 ']'
+ [pyenv-sh-activate:70] venv=anaconda2-5.1.0
+ [pyenv-sh-activate:72] '[' -n /home/zarzen/.pyenv/versions/anaconda3-4.4.0 ']'
+ [pyenv-sh-activate:74] '[' -z /home/zarzen/.pyenv/versions/anaconda3-4.4.0 ']'
+ [pyenv-sh-activate:85] pyenv-virtualenv-prefix anaconda2-5.1.0
+ [pyenv-sh-activate:105] for version in "${versions[@]}"
+ [pyenv-sh-activate:106] [[ anaconda2-5.1.0 != \a\n\a\c\o\n\d\a\2\-\5\.\1\.\0 ]]
+ [pyenv-sh-activate:117] shell=zsh
++ [pyenv-sh-activate:118] pyenv-prefix anaconda2-5.1.0
+ [pyenv-prefix:13] '[' anaconda2-5.1.0 = --complete ']'
+ [pyenv-prefix:18] '[' -n anaconda2-5.1.0 ']'
+ [pyenv-prefix:19] OLDIFS=' 	
'
+ [pyenv-prefix:20] IFS=:
+ [pyenv-prefix:21] export PYENV_VERSION=anaconda2-5.1.0
+ [pyenv-prefix:21] PYENV_VERSION=anaconda2-5.1.0
+ [pyenv-prefix:23] IFS=' 	
'
+ [pyenv-prefix:28] PYENV_PREFIX_PATHS=()
+ [pyenv-prefix:29] OLDIFS=' 	
'
+ [pyenv-prefix:30] IFS=:
+ [pyenv-prefix:31] for version in ${PYENV_VERSION}
+ [pyenv-prefix:32] '[' anaconda2-5.1.0 = system ']'
+ [pyenv-prefix:41] PYENV_PREFIX_PATH=/home/zarzen/.pyenv/versions/anaconda2-5.1.0
+ [pyenv-prefix:43] '[' -d /home/zarzen/.pyenv/versions/anaconda2-5.1.0 ']'
+ [pyenv-prefix:44] PYENV_PREFIX_PATHS=("${PYENV_PREFIX_PATHS[@]}" "$PYENV_PREFIX_PATH")
+ [pyenv-prefix:51] IFS=' 	
'
+ [pyenv-prefix:53] OLDIFS=' 	
'
+ [pyenv-prefix:54] IFS=:
+ [pyenv-prefix:55] echo /home/zarzen/.pyenv/versions/anaconda2-5.1.0
+ [pyenv-prefix:57] IFS=' 	
'
+ [pyenv-sh-activate:118] prefix=/home/zarzen/.pyenv/versions/anaconda2-5.1.0
+ [pyenv-sh-activate:120] '[' -L /home/zarzen/.pyenv/versions/anaconda2-5.1.0 ']'
+ [pyenv-sh-activate:125] [[ /home/zarzen/.pyenv/versions/anaconda3-4.4.0 == \/\h\o\m\e\/\z\a\r\z\e\n\/\.\p\y\e\n\v\/\v\e\r\s\i\o\n\s\/\a\n\a\c\o\n\d\a\2\-\5\.\1\.\0 ]]
+ [pyenv-sh-activate:135] pyenv-sh-deactivate --force --quiet
+ [pyenv-sh-deactivate:12] '[' -z /home/zarzen/.pyenv ']'
+ [pyenv-sh-deactivate:16] unset FORCE
+ [pyenv-sh-deactivate:17] unset QUIET
+ [pyenv-sh-deactivate:19] '[' 2 -gt 0 ']'
+ [pyenv-sh-deactivate:20] case "$1" in
+ [pyenv-sh-deactivate:22] FORCE=1
+ [pyenv-sh-deactivate:35] shift 1
+ [pyenv-sh-deactivate:19] '[' 1 -gt 0 ']'
+ [pyenv-sh-deactivate:20] case "$1" in
+ [pyenv-sh-deactivate:25] QUIET=1
+ [pyenv-sh-deactivate:35] shift 1
+ [pyenv-sh-deactivate:19] '[' 0 -gt 0 ']'
+ [pyenv-sh-deactivate:38] '[' -z /home/zarzen/.pyenv/versions/anaconda3-4.4.0 ']'
++ [pyenv-sh-deactivate:48] basename zsh
+ [pyenv-sh-deactivate:48] shell=zsh
+ [pyenv-sh-deactivate:49] prefix=/home/zarzen/.pyenv/versions/anaconda3-4.4.0
+ [pyenv-sh-deactivate:51] [[ /home/zarzen/.pyenv/versions/anaconda3-4.4.0 == \/\h\o\m\e\/\z\a\r\z\e\n\/\.\p\y\e\n\v\/\v\e\r\s\i\o\n\s ]]
+ [pyenv-sh-deactivate:54] venv=anaconda3-4.4.0
+ [pyenv-sh-deactivate:57] '[' -n '' ']'
+ [pyenv-sh-deactivate:62] '[' -x /home/zarzen/.pyenv/versions/anaconda3-4.4.0/bin/conda ']'
+ [pyenv-sh-deactivate:63] shopt -s nullglob
+ [pyenv-sh-deactivate:64] case "${shell}" in
+ [pyenv-sh-deactivate:72] echo 'unset CONDA_PREFIX'
+ [pyenv-sh-deactivate:75] shopt -u nullglob
+ [pyenv-sh-deactivate:78] '[' -n '' ']'
+ [pyenv-sh-deactivate:98] case "${shell}" in
+ [pyenv-sh-deactivate:106] cat
+ [pyenv-sh-deactivate:114] '[' -n root ']'
+ [pyenv-sh-deactivate:115] case "${shell}" in
+ [pyenv-sh-deactivate:120] echo 'unset CONDA_DEFAULT_ENV;'
+ [pyenv-sh-deactivate:125] case "${shell}" in
+ [pyenv-sh-deactivate:135] cat
+ [pyenv-sh-deactivate:144] case "${shell}" in
+ [pyenv-sh-deactivate:154] cat
+ [pyenv-sh-deactivate:163] case "${shell}" in
+ [pyenv-sh-deactivate:168] cat
+ [pyenv-sh-deactivate:177] case "${shell}" in
+ [pyenv-sh-deactivate:186] cat
+ [pyenv-sh-activate:137] '[' -n '' ']'
+ [pyenv-sh-activate:141] '[' -z 1 ']'
+ [pyenv-sh-activate:164] case "${shell}" in
+ [pyenv-sh-activate:172] cat
+ [pyenv-sh-activate:180] '[' -x /home/zarzen/.pyenv/versions/anaconda2-5.1.0/bin/conda ']'
+ [pyenv-sh-activate:181] [[ /home/zarzen/.pyenv/versions/anaconda2-5.1.0 != \/\h\o\m\e\/\z\a\r\z\e\n\/\.\p\y\e\n\v\/\v\e\r\s\i\o\n\s\/\a\n\a\c\o\n\d\a\2\-\5\.\1\.\0 ]]
+ [pyenv-sh-activate:184] CONDA_DEFAULT_ENV=root
+ [pyenv-sh-activate:186] case "${shell}" in
+ [pyenv-sh-activate:191] echo 'export CONDA_DEFAULT_ENV="root";'
+ [pyenv-sh-activate:196] '[' -n '' ']'
+ [pyenv-sh-activate:213] PYENV_VIRTUALENV_DISABLE_PROMPT=
+ [pyenv-sh-activate:214] PYENV_VIRTUALENV_DISABLE_PROMPT=
+ [pyenv-sh-activate:216] '[' -z '' ']'
+ [pyenv-sh-activate:217] case "${shell}" in
+ [pyenv-sh-activate:224] '[' -z 1 ']'
+ [pyenv-sh-activate:227] cat
+ [pyenv-sh-activate:236] '[' -x /home/zarzen/.pyenv/versions/anaconda2-5.1.0/bin/conda ']'
+ [pyenv-sh-activate:237] shopt -s nullglob
+ [pyenv-sh-activate:238] case "${shell}" in
+ [pyenv-sh-activate:246] CONDA_PREFIX=/home/zarzen/.pyenv/versions/anaconda2-5.1.0
+ [pyenv-sh-activate:247] echo 'export CONDA_PREFIX="/home/zarzen/.pyenv/versions/anaconda2-5.1.0";'
+ [pyenv-sh-activate:252] for script in "${prefix}/etc/profile.d"/*.sh
+ [pyenv-sh-activate:253] echo '. "/home/zarzen/.pyenv/versions/anaconda2-5.1.0/etc/profile.d/conda.sh";'
+ [pyenv-sh-activate:257] shopt -u nullglob
```

**Comment by apapanico** [comment]
Did this fix work for people?  I am still running into this issue.  

Specs: MacOS Mojave, brew installed pyenv and git, bash 4.4.23.

```
:~$ pyenv --version
pyenv 1.2.7
:~$ brew list | grep pyenv
pyenv
pyenv-virtualenv
pyenv-which-ext   # I tried with and without this plugin. makes no difference
:~$ git submodule 
pyenv: gettext.sh: command not found

The `gettext.sh' command exists in these Python versions:
  anaconda3-5.2.0

/usr/local/Cellar/git/2.19.1/libexec/git-core/git-sh-setup: line 93: eval_gettext: command not found
fatal: not a git repository (or any of the parent directories): .git
:~$ pyenv which gettext.sh
pyenv: gettext.sh: command not found

The `gettext.sh' command exists in these Python versions:
  anaconda3-5.2.0
```

The shim looks correct though, if `gettext.sh` could be found:
```
[ -n "$PYENV_DEBUG" ] && set -x
export PYENV_ROOT="/usr/local/var/pyenv"
program="$("/usr/local/Cellar/pyenv/1.2.7/libexec/pyenv" which "${BASH_SOURCE##*/}")"
if [ -e "${program}" ]; then
  . "${program}" "$@"
fi
```

If I uninstall the anaconda distribution and do `pyenv rehash`, everything works again.  So how does git find `gettext.sh` normally?

**Comment by sebhahn** [comment]
I'm also still running into this issue!

**Comment by matwerber1** [comment]
same issue.

**Comment by kondongx** [comment]
same issue, also with pandoc

**Comment by sebhahn** [comment]
@yyuu can we re-open this issue? Do you see any possibility to fix this?

**Comment by mazzma12** [comment]
Same issue

**Comment by mazzma12** [comment]
The issue is still here, but this seems to fix it : 

> The actual _problem_ is in git-core. It seems it's trying to search `gettext.sh` from `$PATH` then `source` it.
> 
> https://github.com/git/git/blob/v2.13.3/git-sh-i18n.sh#L46
> 
> As a tentative workaround, setting something in `GIT_INTERNAL_GETTEXT_TEST_FALLBACKS` might work.
> 
> ```
> export GIT_INTERNAL_GETTEXT_TEST_FALLBACKS=1
> ```

**Comment by gangmax** [comment]
I was running into this issue when executing the "git stash list" command on my Mac(I installed "git", "pyenv" and "miniconda"):

```
> git stash list
pyenv: gettext.sh: command not found

The `gettext.sh' command exists in these Python versions:
  miniconda3-4.3.30
  miniconda3-4.3.30/envs/es

/usr/local/Cellar/git/2.19.1/libexec/git-core/git-sh-setup: line 93: eval_gettext: command not found
```

After I adding the line below into my "~/.zshrc" file, the problem is resolved:

`export GIT_INTERNAL_GETTEXT_TEST_FALLBACKS=1`

**Comment by albireox** [comment]
Still seeing this problem with fish, regardless of whether I use `export GIT_INTERNAL_GETTEXT_TEST_FALLBACKS=1`. The only way to fix the problem seems to be removing the gettext shims manually.
