### ISSUE TITLE
macOS High Sierra: ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

### ISSUE THREAD

**Issue by uber1geek** [pyenv/pyenv#993]
I am having this issue on mac os high sierra(10.13) even with setting CFLAGS and LDFLAGS correctly using brew --prefix

**Comment by BruceFrankWang** [comment]
@uber1geek 

I can finish this step successfully.

first:
brew install readline openssl xz

and Homebrew said both readline and openssl is keg-only. so I wrote a .sh file to export environment variables:

# ~/.env-exporter
# zlib
export CFLAGS="-I$(xcrun --show-sdk-path)/usr/include"

# Add readline path to environment variable
export CFLAGS="-I$(brew --prefix readline)/include $CFLAGS"
export LDFLAGS="-L$(brew --prefix readline)/lib $LDFLAGS"

# Add openssl path to environment variable
export CFLAGS="-I$(brew --prefix openssl)/include $CFLAGS"
export LDFLAGS="-L$(brew --prefix openssl)/lib $LDFLAGS"

# Add SQLite path to environment variable
export CFLAGS="-I$(brew --prefix sqlite)/include $CFLAGS"
export LDFLAGS="-L$(brew --prefix sqlite)/lib $LDFLAGS"


every time I want install a Python:
 # source ~/.env-exporter
# pyenv install -v 2.7.13

I failed at the step of installing pip, cause of could not build the pyexpat module.

Hope helpful, and wish I can install 2.7.13 & 3.6.2

**Comment by natecox** [comment]
I'm currently experiencing this issue on a clean install of High Sierra. I was able to get openssl recognized using the above script, however I'm now failing because `pyexpat` can't be found (as referenced in the bottom of the last post). Is this a known issue?

**Comment by uber1geek** [comment]
I would suggest removing the old installation and install using homebrew. The problem turned out to be the openssl hadn't actually successfully installed (even though homebrew reported that it had). run brew uninstall openssl && brew install openssl && CFLAGS="-I$(brew --prefix openssl)/include" LDFLAGS="-L$(brew --prefix openssl)/lib" pyenv install 3.6.2

**Comment by uber1geek** [comment]
or simply,  `brew install pyenv`

**Comment by BruceFrankWang** [comment]
@uber1geek You are right. Do not install pyenv via pyenv-installer, instead of brew.

**Comment by jlott** [comment]
This can be solved pretty easily without installing homebrew. See my comment here https://github.com/pyenv/pyenv/issues/950#issuecomment-334612904

**Comment by kryptek** [comment]
I started getting this issue once I upgraded to High Sierra. I followed the instructions above to uninstall and reinstall openssl and it fixed the issue -- I can now compile python successfully. 

Thanks!

**Comment by Voleking** [comment]
`brew install pyenv` doesn't help. 
In fact, I install `openssl` and `pyenv` both by homebrew.
`CFLAGS="-I$(brew --prefix openssl)/include" LDFLAGS="-L$(brew --prefix openssl)/lib" pyenv install 3.6.3` does fix this issue.

**Comment by wdeer** [comment]
I was running into the same issue on High Sierra after installing pyenv, xz, readline, and openssl all from homebrew.. but as @Voleking stated, setting CFLAGS and LDFLAGS works..

to not have to type it in every time just add the following alias to your .profile, .bashrc, .zshrc or whatever.. 

	alias pyenv='CFLAGS="-I$(brew --prefix openssl)/include" LDFLAGS="-L$(brew --prefix openssl)/lib" pyenv'

**Comment by justinfinkle** [comment]
I have the same problem, even when setting `CFLAGS` and `LDFLAGS` and suggested.

Any other suggestions that worked?

**Comment by mpasternak** [comment]
@wdeer , this actually makes your shell start up a lot of slower, as the commands included in alias are being expanded every time the shell is run. On my 2015 MBP it gives a few seconds of delay. 

I came here because I also have the same problem. Looking into other solutions.

**Comment by heynairb** [comment]
Guys if you're using brew and you hit this problem, the most recent version actually works now... Run these commands:
brew unlink pyenv
brew install pyenv --HEAD
it should work now...

**Comment by natecox** [comment]
@heynairb do you know if there's a workaround for missing `pyexpat`? When I try to build python on High Sierra I get the following:

```~
➜ pyenv install 2.7.14
python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-2.7.14.tar.xz...
-> https://www.python.org/ftp/python/2.7.14/Python-2.7.14.tar.xz
Installing Python-2.7.14...
python-build: use readline from homebrew
Installing pip from https://bootstrap.pypa.io/get-pip.py...
error: failed to install pip via get-pip.py

BUILD FAILED (OS X 10.13.1 using python-build 20160602)

Inspect or clean up the working tree at /var/folders/y2/6bz4kq_s029_syhvswcw7w6w0000gn/T/python-build.20171204134242.61393
Results logged to /var/folders/y2/6bz4kq_s029_syhvswcw7w6w0000gn/T/python-build.20171204134242.61393.log

Last 10 log lines:
    info = _mac_ver_xml()
  File "/Users/nate/.pyenv/versions/2.7.14/lib/python2.7/platform.py", line 741, in _mac_ver_xml
    pl = plistlib.readPlist(fn)
  File "/Users/nate/.pyenv/versions/2.7.14/lib/python2.7/plistlib.py", line 78, in readPlist
    rootObject = p.parse(pathOrFile)
  File "/Users/nate/.pyenv/versions/2.7.14/lib/python2.7/plistlib.py", line 401, in parse
    from xml.parsers.expat import ParserCreate
  File "/Users/nate/.pyenv/versions/2.7.14/lib/python2.7/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: No module named pyexpat```

**Comment by natecox** [comment]
Nevermind on the above, I forgot that my `LDFLAGS` and `CFLAGS` were still set to get openssl to work. 

For posterity, removing them from `.zshrc` allowed `pyexpat` to be found properly.

**Comment by sanghapriya** [comment]
I got it working in _macOS High Sierra 10.13.1_ by installing openssl using `brew install openssl`, setting the `CFLAGS` to `CFLAGS="-I$(brew --prefix openssl)/include" ` and `LDFLAGS` to `LDFLAGS="-L$(brew --prefix openssl)/lib"` and then following @heynairb  comment to install `pyenv` using `brew install pyenv --HEAD`

**Comment by brunojppb** [comment]
Did what @sanghapriya said and it worked.

```sh
$ brew install openssl
```
Added to my `.zshrc`(I am using [o-my-zsh](https://github.com/robbyrussell/oh-my-zsh))
```sh
export CFLAGS="-I$(brew --prefix openssl)/include"
export LDFLAGS="-L$(brew --prefix openssl)/lib"
```

and ran it again:
```sh
$ brew install pyenv --HEAD
```

**Comment by schinwang** [comment]
Here's my solution:
1) install readline xy openssl pyenv via homebrew ,
2) and if you've already installed these pkgs
brew upgrade openssl pyenv  to the latest version
3) pyenv install your_version

**Comment by jenshnielsen** [comment]
I think this issue was fixed by https://github.com/pyenv/pyenv/pull/1025 which means that it's fixed in pyenv 1.2.0. I guess this issue can close?

**Comment by Trefex** [comment]
@jenshnielsen I had this issue and just using latest versions of all mentioned packages worked.

**Comment by webknjaz** [comment]
This issue still happens https://github.com/pyenv/pyenv/issues/1066#issuecomment-357808697

**Comment by gianchub** [comment]
Hello, this is happening to me too, and even though I tried everything is this thread, it seems I cannot fix it. Any help would be much appreciated!

```
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-9.0.1 setuptools-28.8.0
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (OS X 10.13.3 using python-build 20160602)

Inspect or clean up the working tree at /var/folders/6_/px0c3dd15jq57bkhjrt9d9m40000gn/T/python-build.20180302124832.24199
Results logged to /var/folders/6_/px0c3dd15jq57bkhjrt9d9m40000gn/T/python-build.20180302124832.24199.log

Last 10 log lines:
			upgrade) ensurepip="--upgrade" ;; \
			install|*) ensurepip="" ;; \
		esac; \
		 ./python.exe -E -m ensurepip \
			$ensurepip --root=/ ; \
	fi
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-9.0.1 setuptools-28.8.0
```
I'm using pyenv 1.2.2 from brew.

**Comment by etienne-bondot** [comment]
@schinwang Solution works for me, upgrading brew pkgs resolved the issue.

**Comment by maplethorpej** [comment]
I fixed this simply by updating pyenv: `brew upgrade pyenv`

**Comment by jenshnielsen** [comment]
I am seeing this failing again with python 3.7 betas. This seems to be due to https://bugs.python.org/issue32598 improving openssl configuration options. 

For homebrew the following seems to work.

```
export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig/
pyenv install 3.7.0b2
```

**Comment by jalevin** [comment]
Besides pyenv I also could not install ruby versions via rbenv. At this point I started looking at the system. I'd recently upgraded and used the migration assistant to move to a new machine.

1. go to Applications and run Xcode. I had additional packages install
2. run brew doctor. if any files in /usr/local/include show up you have 2 options. Either rename the directory to something else like include_old or remove the offending entries. I chose the first.

``` sudo mv /usr/local/include /usr/local/include_old ```
``` sudo mkdir /usr/local/include ```
``` sudo chown $YOU_USERNAME:admin /usr/local/include ```

afterward, I was able to install ruby and python versions

**Comment by marcwww** [comment]
Hey guys, I just `brew update pyenv` and all works again.

**Comment by cliff76** [comment]
I just wasted my entire morning fighting this issue on OSX Sierra 10.12.6 (not High Sierra). I was running pyenv installed from the bash script pyenv-installer. I tried just about every solution from installing openssl via brew, to uninstalling openssl and reinstalling, to downloading the headers and setting the include separately, to including CPPFLAGS as well as CFLAGS settings. Nothing worked! 

The ONLY solution for me was to install pyenv via brew and delete the version installed via the pyenv-installer. I don't like installing programs in root folders and would have rather used the pyenv-installer since it puts things in my home dir but this was the only solution.

**Comment by ubidefeo** [comment]
@cliff76 I had everything installed via `homebrew` but it kept failing.
I then realised that upgrading from Sierra to High Sierra and installing XCode 9.x might have broken something so I ran
`xcode-select --install` and I got the popup to install/refresh all the command line tools.

After that it installed fine via pyenv :)

**Comment by aramay** [comment]
I had to run -
`brew upgrade pyenv`

**Comment by Kezzsim** [comment]
This issue is being exacerbated to an insane degree by the fact that apparently Brew refuses to host openSSL 1.0.2t instead opting for 1.1.1 only; Python 2.7 can't function with 1.1.1 (apparently) and so I'm stuck at this error over and over again:

`pyenv install 2.7.10
python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-2.7.10.tar.xz...
-> https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tar.xz
Installing Python-2.7.10...
patching file ./Lib/site.py
python-build: use readline from homebrew
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (OS X 10.13.6 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/qv/bywj26qd779_8jb49r151lrm0000gp/T/python-build.20191130235433.66266
Results logged to /var/folders/qv/bywj26qd779_8jb49r151lrm0000gp/T/python-build.20191130235433.66266.log

Last 10 log lines:
rm -f /usr/local/var/pyenv/versions/2.7.10/share/man/man1/python.1
(cd /usr/local/var/pyenv/versions/2.7.10/share/man/man1; ln -s python2.1 python.1)
if test "xno" != "xno"  ; then \
		case no in \
			upgrade) ensurepip="--upgrade" ;; \
			install|*) ensurepip="" ;; \
		esac; \
		 ./python.exe -E -m ensurepip \
			$ensurepip --root=/ ; \
	fi
`

**Comment by Adzz** [comment]
Same issue trying to install python 3.5.2 which is apparently compatible with openssl 1.1:
```sh
CFLAGS="-I$(brew --prefix openssl)/include" \
LDFLAGS="-L$(brew --prefix openssl)/lib" asdf install python 3.5.2
python-build 3.5.2 /Users/adamlancaster/.asdf/installs/python/3.5.2
python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-3.5.2.tar.xz...
-> https://www.python.org/ftp/python/3.5.2/Python-3.5.2.tar.xz
Installing Python-3.5.2...
patching file Lib/venv/scripts/posix/activate.fish
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (OS X 10.15.2 using python-build 1.2.16-2-g36fc10fb)

Inspect or clean up the working tree at /var/folders/gm/84m52gh16sx9g7l_gln_w77r0000gn/T/python-build.20200113113216.50262
Results logged to /var/folders/gm/84m52gh16sx9g7l_gln_w77r0000gn/T/python-build.20200113113216.50262.log

Last 10 log lines:
(cd /Users/adamlancaster/.asdf/installs/python/3.5.2/share/man/man1; ln -s python3.5.1 python3.1)
if test "xupgrade" != "xno"  ; then \
		case upgrade in \
			upgrade) ensurepip="--upgrade" ;; \
			install|*) ensurepip="" ;; \
		esac; \
		 ./python.exe -E -m ensurepip \
			$ensurepip --root=/ ; \
	fi
Ignoring ensurepip failure: pip 8.1.1 requires SSL/TLS
```

**Comment by joony0123** [comment]
For those still having the same issue please try the steps below. None of the solutions above worked for me. It turns out I need to let pyenv install his own compatible openssl version

1. 
`brew uninstall openssl`

2. 
`pyenv install 2.7.3`

You will see then that it is installing a different version from the latest openssl version
`Downloading openssl-1.0.2k.tar.gz...
-> https://pyenv.github.io/pythons/6b3977c61f2aedf0f96367dcfb5c6e578cf37e7b8d913b4ecb6643c3cb88d8c0
Installing openssl-1.0.2k...
ah Installed openssl-1.0.2k to /Users/joonkim/.pyenv/versions/2.7.3`

Good luck!

**Comment by satchelfrench** [comment]
@joony0123 's suggestion worked perfectly for me!

I managed to fix pyenv install for 3.7.X by reinstalling Xcode command line tools, but it still didn't work for 2.XX versions. I had openssl 1.1 installed through home-brew, but it didn't occur to me that the earlier versions of python weren't compatible with openssl@1.1.  

This is what I did to get everything working on my system. (adapted a bit of @joony0123's)

1. `brew uninstall openssl`
2. `rm -rf ~/Library/Developer/CommandLineTools`
3. `brew upgrade pyenv` or `brew install pyenv --HEAD` as per @heynairb 's suggestion
4. `xcode-select --install` 

open up Xcode GUI and allow it to complete the installation of some more packages

finally,
5. `pyenv install X.X.X`

Running on 10.15.2 Catalina

Hope this helps!

So finally I opened xcode Gui and it had some remaining packages to install

**Comment by liriarte** [comment]
None of the solutions above seem to work with Python 2.6.0. Any ideas for this specific version?

**Comment by shentonfreude** [comment]
@joony0123's solution worked for me, where every other mechanism (CPPFLAGS, LDFLAGS) did not. Uninstalling brew's openssl makes pyenv download a compatible openssl which it then installs in its private directory, and which it successfully builds python against. Then you can reinstall brew's openssl to restore the functionality of its dependents. 

macOS Mojave 10.14.6, pyenv-1.12.16, Python-3.5.2 with openssl-1.0.2k.

**Comment by hsiunien** [comment]
> For those still having the same issue please try the steps below. None of the solutions above worked for me. It turns out I need to let pyenv install his own compatible openssl version
> 
> 
> `brew uninstall openssl`
> 
> 
> `pyenv install 2.7.3`
> 
> You will see then that it is installing a different version from the latest openssl version
> `Downloading openssl-1.0.2k.tar.gz... -> https://pyenv.github.io/pythons/6b3977c61f2aedf0f96367dcfb5c6e578cf37e7b8d913b4ecb6643c3cb88d8c0 Installing openssl-1.0.2k... ah Installed openssl-1.0.2k to /Users/joonkim/.pyenv/versions/2.7.3`
> 
> Good luck!

It worked for me,because if I ran brew install openssl, it installed openssl@1.1 and it didn't work for me , still said  no OpenSLl, and I use this method solve it ,and it installed   openssl-1.0.2k, thanks

**Comment by gobftald** [comment]
> > For those still having the same issue please try the steps below. None of the solutions above worked for me. It turns out I need to let pyenv install his own compatible openssl version
> > `brew uninstall openssl`
> > `pyenv install 2.7.3`
> > You will see then that it is installing a different version from the latest openssl version
> > `Downloading openssl-1.0.2k.tar.gz... -> https://pyenv.github.io/pythons/6b3977c61f2aedf0f96367dcfb5c6e578cf37e7b8d913b4ecb6643c3cb88d8c0 Installing openssl-1.0.2k... ah Installed openssl-1.0.2k to /Users/joonkim/.pyenv/versions/2.7.3`
> > Good luck!
> 
> It worked for me,because if I ran brew install openssl, it installed openssl@1.1 and it didn't work for me , still said no OpenSLl, and I use this method solve it ,and it installed openssl-1.0.2k, thanks

How can you manage it? You cannot uninstall openssl since it is a dependeny of pyenv itself. So you (more precisely me) cannot call "pyenv install 2.7.3" without installed openssl, to install their own version of openssl, since if you van to use pyenv openssl was installed during its installlation. Deadlock.

**Comment by zenbaku** [comment]
For reference, I didn't have to uninstall openssl@1.1 from homebrew, but rather, install a more updated version of python 2.7. `2.7.12` did not work, but `2.7.13` worked.

After installing `readline`, `xz`, `openssl` and `pyenv` with homebrew I successfully installed python2 using this command:

```
CONFIGURE_OPTS="--with-openssl=/usr/local/opt/openssl@1.1" LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" LD_RUN_PATH="/usr/local/opt/openssl@1.1/lib" CPPFLAGS="-I/usr/local/opt/openssl@1.1/include" CFLAGS="-I/usr/local/opt/openssl@1.1/include" pyenv install -v 2.7.13
```

It seems some versions of python2 won't work with openssl 1.1, which was deprecated from homebrew, even when explicitly set using env flags.

**Comment by lybwb** [comment]
sudo PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install -v 2.7.6

it's seem use for me.

**Comment by bhy** [comment]
For someone encountering this error message when installing PyPy, this is a bug in PyPy 7.3.1: https://foss.heptapod.net/pypy/pypy/issues/3229

**Comment by mathsyouth** [comment]
> For someone encountering this error message when installing PyPy, this is a bug in PyPy 7.3.1: https://foss.heptapod.net/pypy/pypy/issues/3229
On macOS Catalina, I met this error message when installing PyPy 7.3.1. However, when changing to PyPy 7.3.0, errors disappear. Thanks!

**Comment by rraallvv** [comment]
Has anyone been able to install 2.5.6 on macOS using homebrew?

It seems the the script `python-build` can't detect sqlite nor openssl, I've tried with the command below but it doesn't work either:

```
CONFIGURE_OPTS="--with-openssl=$(brew --prefix openssl)" \
LD_RUN_PATH="$(brew --prefix openssl)/lib" \
CPPFLAGS="-I$(brew --prefix openssl)/include" \
CFLAGS="-I$(xcrun --show-sdk-path)/usr/include -I$(brew --prefix readline)/include $CFLAGS -I$(brew --prefix openssl)/include -I$(brew --prefix sqlite)/include $CFLAGS" \
LDFLAGS="-L$(brew --prefix readline)/lib $LDFLAGS -L$(brew --prefix openssl)/lib $LDFLAGS -L$(brew --prefix sqlite)/lib $LDFLAGS" \
pyenv install 2.5.6
```

**Comment by doctorduke** [comment]
Okay. I had a different experience. I'm just cross posting this in the locations that partially helped me so if someone ends up there related to this it might help. Sorry if this isn't helpful to this direct train of thought or what helps you specifically.
This was all wrote in Notion so I apologize if it's formatting is off. Here's the link to it in my Notion. You can send me comments there and I should get them quickly. Hit me up however you can find a way if the link gets broken. I'll more than likely update there before I update everywhere else.

https://www.notion.so/Working-on-getting-python-and-pip-821f4b2d90034f7595ef5470f6b80286

Pre-preface: pardon my dark humour but I have had a few days of banging my head against a wall on a few other things and this was the icing on the cake.


To preface what I have been trying to do is install basic command line tools for the languages I use and are called for in some new things I'm trying to learn on a fresh OSX install. I'm doing this on two fresh Big Sur installs because I like to keep my machines in parity. The idea of that is to be able to easily swap between my machines if one is running something intense and I want to move on to something else.

This is done on Big Sur 11.0.1 and brew version 2.7.7.

I'm trying to give as comprehensive a version of the final steps and not the hours upon hours I have spent working to fix this.

Also, I'd like to mention I'm familiar with these tools in no way an expert so this was not fun and I imagine any new user being given a new computer and having to do this would be so freaking discouraged its gross. Beyond that I'm on a 4Mbit connection because I have moved to a rural area with no good alternatives. So this has been excruciating having to also deal with failed huge downloads after hours of waiting for them to finish. Having previously mentioned that I am doing this on 2 machines I'd like to also point out how painful a system like the Mac App Store is when you have to spend hours just to install Xcode and then do it again on a second machine because 1. There doesn't seem to be a straighforward way to share locally your installs 2. I'm sure there are other ways to do direct downloads and other tricks but I wasn't trying to solve that problem. I was just trying to install 2 versions of python and tools related to it.

In the end using 'pyenv' I was able to install Python 3.8.0. That let me see that there was some hope but I was trying to install a Python 2.7.x version. I was able to get both installed but need to try again from scratch to see if they can work in a different order.

I have had many many errors come through. I may not get them all but I had this warning

So to be honest I can't even remember what the task I was setting out to do was. OH. I was trying to get started working with [hass.io](http://hass.io) (Home Assistant) and install it on one of my Macs. I was told to use the command 'virtual-env'. I can't remember the specifics because I've been at this 8 hours today and tried what feels like a million things. If you could see how great a noose I worked on while waiting for failures! (I kid.) Somehow virtual-env lead me to needing to install pip I think. I can't remember if it was trying to get pip or pyenv installed but there were a bunch of errors about permissions. I must have cleaned my log but they were errors about permissions for /usr/local.

## Permission errors installing pyenv

The first step to doing this I found was disabling SIP (System Integrity Protection). I was hoping to find a way to do this from the command line but all the examples of how to do this didn't work for me. So I ended up 

1. Shut down your Mac
2. Ensure your Mac has shut down.
3. It probably didn't.
4. Do it again.
5. Nope.
6. Just hold the power button for 4 minutes and hope it works.
7. Once it's shutdown Hold CMD+R 
8. Then in addition to having CMD+R held press the power button until it seems like your Mac may finally start to boot. Its different every time!
9. You can and maybe should release CMD+R when you see the Apple logo. If it worked you should see a large apple if running at a resolution during normal operations.
10. Select your language. (I guess now is the best time to mention barring anything blowing my mind this will all be in English.)
11. You'll get presented with a menu eventually that has a bunch of options one of which will be "Disk Utility". You're almost through Step -10!
12. At the top menu under Utilities select terminal.
13. In the terminal window that I hope for your has opened input the following command.

    ```bash
    csrutil disable
    ```

    - credit stackoverflow post

        [https://stackoverflow.com/questions/63312303/is-there-a-way-to-change-a-read-only-file-system-to-a-writable-file-system-on-ma](https://stackoverflow.com/questions/63312303/is-there-a-way-to-change-a-read-only-file-system-to-a-writable-file-system-on-ma)

14. Then you can restart. I'll note everything I ever read says turn it back on after. Hell no in my opinion. This setting has never once to my knowledge done anything but cause me headaches and waste hours upon hours of my time. {EXPLETIVE DELETED} that.

Now that SIP (more like BLOWS) is disabled you can proceed to your next error.

### You still can't modify the permission on this directory

Now you are able to modify the read write permissions on the contents of the /usr/local directory. This is accomplished with the following.

```bash
sudo chmod -R 775 /usr/local
```

You'd think that would be enough but 

```bash
Error: The following directories are not writable by your user:
/usr/local/lib/pkgconfig
/usr/local/share/info
/usr/local/share/man/man3
/usr/local/share/man/man5
```

Luckily the output about this gives you the answer, at least in my situation it did.

1. Enter the following in your terminal 

```bash
sudo chown -R $(whoami) /usr/local/lib/pkgconfig /usr/local/share/info /usr/local/share/man/man3 /usr/local/share/man/man5
```

Congrats! You have only begun to understand the frustration if you were trying to get further than this and ended up here.

You can now install pyenv with brew.

```bash
brew install pyenv
```

Don't know how to help you if that didn't work. 

## What ended up being Python 3.8.0 instead of 2.7.9 installation steps and errors.

So from here. Again let me say I'm not an expert in this stuff. I have a bad habit of not reading every line of spam that comes out when working in the command line and the process takes forever. From here I did follow what it said about some errors with OpenSSL and added those to my bash_profile and sourced it in the window. Something I'll say may not be glaringly obvious to some that aren't pros here is that the output specifically says this.

```bash
If you need to have openssl@1.1 first in your PATH, run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> /Users/doctorduke/.bash_profile

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

For compilers to find readline you may need to set:
  export LDFLAGS="-L/usr/local/opt/readline/lib"
  export CPPFLAGS="-I/usr/local/opt/readline/include"

For pkg-config to find readline you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/readline/lib/pkgconfig"
```

To some you may be like "Obviously." To other who don't do this all the time and/or it's rare you have to you might get caught up doing exactly what this thing says and setting. NOT appending these values when both are needed. IT SPECIFICALLY says set =. That's an assignment to an exact value.  When everything is failing you probably try and follow the instructions to a T.

So I add a few experimental things to my bash_profile and without updating it to what was in the end that worked it had these in it related to getting pyenv to install (what at this point was still an attempt at 2.7.9).

```bash
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export LDFLAGS="-L/usr/local/opt/zlib/lib -L/usr/local/opt/bzip2/lib"
export CPPFLAGS="-I/usr/local/opt/zlib/include -I/usr/local/opt/bzip2/include"

export PATH="$HOME/.pyenv/bin:$PATH"
export PATH="/usr/local/bin:$PATH"

export PATH="/usr/local/opt/sqlite/bin:$PATH"
export PKG_CONFIG_PATH="/usr/local/opt/sqlite/lib/pkgconfig
```

Again, this has been hours of working with extremely similar modifications across multiple machines. I'm trying to hit every error I saw and what got around it but I doubt I will. Some parts may be out of order or missed because I cleaned some consoles a couple times and overwrote a few things when something failed too many times.

### LOTS of messages about zlib not working.

So if you go the route of doing the xcode command line tools. On Big Sur 11.0.1 I ended up, because one of the many results that said it solved my problem (which this did not seem to directly solve my problem) but I encountered a bunch of steps that there are bugs in versions of the command line tools around version 12.2 in beta or and a few others. I ended up wasting 2 hours of my life having to upgrade to Xcode 12.4 (separately on 2 machines) and the command line tool (this went okay because I found a direct link to the .dmg and was able to Airdrop it to my second machine when I verified the download. [https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_12.4/Command_Line_Tools_for_Xcode_12.4.dmg](https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_12.4/Command_Line_Tools_for_Xcode_12.4.dmg)

Further steps say two options I believe are the same thing but I'm not sure. One is use xcode-select and blah. The following was the next step in getting me somewhere.

Via this link

[https://github.com/pyenv/pyenv/issues/1737](https://github.com/pyenv/pyenv/issues/1737)

(Oh yeah. PS. I hit up the freaking Common Build Errors page. Thanks for nothing the guys that go out of their way to say this when most people have already done it. You don't need to tell people to do this over and over when it's right there in the output. The info isn't always up to date and again FRESH INSTALL of everything so it should be straight forward. Still none of this info was compiled there.)

What did help was this awesome dude at the above link. Per him in that link the following two steps got me (and these are exactly following his instructions. Which is why I got Python 3.8.0)

## **Step 1 Align command-line tools**

Open Xcode-beta.appGo to Preference > LocationsSelect the right version of command-line tools

## **Step 2 Install python**

In this case, I installed 3.8.0. If you want to install a different version, you will need to change the version in the following command.`CFLAGS="-I$(brew --prefix openssl)/include -I$(brew --prefix bzip2)/include -I$(brew --prefix readline)/include -I$(xcrun --show-sdk-path)/usr/include" LDFLAGS="-L$(brew --prefix openssl)/lib -L$(brew --prefix readline)/lib -L$(brew --prefix zlib)/lib -L$(brew --prefix bzip2)/lib" pyenv install --patch 3.8.0 < <(curl -sSL https://github.com/python/cpython/commit/8ea6353.patch\?full_index\=1)`

I just copied and pasted to not screw anything up.

But this seemed to work! The wrong version, some version of 3 which wasn't what I was trying to get to yet. Now I'm ahead of the game though. Now let's just change the version number as mentioned further in the post to the one we were going for and it'll be good.

## Crap I forgot about this and only remembered when I was almost at the end

I execute this command before I got 3.8.0 to install properly. Not sure what layer of work it helped but I vaguely remember it getting rid of something. 

```bash
brew reinstall zlib bzip2
```

## Python 2.7.9 steps and errors.

```bash
CFLAGS="-I$(brew --prefix openssl)/include -I$(brew --prefix bzip2)/include -I$(brew --prefix readline)/include -I$(xcrun --show-sdk-path)/usr/include" LDFLAGS="-L$(brew --prefix openssl)/lib -L$(brew --prefix readline)/lib -L$(brew --prefix zlib)/lib -L$(brew --prefix bzip2)/lib" pyenv install --patch 2.7.9 < <(curl -sSL https://github.com/python/cpython/commit/8ea6353.patch\?full_index\=1)
```

Yay right? No. Not yay. More of the same about the OpenSSL being wrong. 

From here I'm going to spare you an even more long winded explanation about all the different CFLAGS and LFLAGS I tried to vary between to get this to work. 

At some point I was noticing before the OpenSSL error that there was a warning about SQlite3 not compiling so I decided to fix that incase it was causing me issues with OpenSSL. This didn't help the exact error I was getting but getting rid of warnings makes the errors easier to distinguish. 

```bash
brew install sqlite3
```

### After getting SQLite3 reinstalled correctly.

```bash
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems

BUILD FAILED (OS X 11.0.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/6z/cngcgtk97zvdh818_gg5qytc0000gn/T/python-build.20210204152125.11840
Results logged to /var/folders/6z/cngcgtk97zvdh818_gg5qytc0000gn/T/python-build.20210204152125.11840.log
```

Okay. The above may not be the final error. There's a few variations of the ones I was getting. This one was unique.

```bash
Py_FatalError("abort() called from Python code didn't abort!");
    ^~~~~~~~~~~~~
1 warning and 1 error generated.
make: *** [Modules/posixmodule.o] Error 1
make: *** Waiting for unfinished jobs....

BUILD FAILED (OS X 11.0.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/6z/cngcgtk97zvdh818_gg5qytc0000gn/T/python-build.20210204134530.6409
Results logged to /var/folders/6z/cngcgtk97zvdh818_gg5qytc0000gn/T/python-build.20210204134530.6409.log
```

I think that might have been trying to do a 2.6 version though.

Here is another

```bash
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems

BUILD FAILED (OS X 11.0.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/6z/cngcgtk97zvdh818_gg5qytc0000gn/T/python-build.20210204151421.87649
Results logged to /var/folders/6z/cngcgtk97zvdh818_gg5qytc0000gn/T/python-build.20210204151421.87649.log

Last 10 log lines:
rm -f /Users/doctorduke/.pyenv/versions/2.7.9/share/man/man1/python.1
(cd /Users/doctorduke/.pyenv/versions/2.7.9/share/man/man1; ln -s python2.1 python.1)
if test "xno" != "xno"  ; then \
		case no in \
			upgrade) ensurepip="--upgrade" ;; \
			install|*) ensurepip="" ;; \
		esac; \
		 ./python.exe -E -m ensurepip \
			$ensurepip --root=/ ; \
	fi
```

Yet another version

```bash
Installing Python-2.7.7...

ERROR: The Python zlib extension was not compiled. Missing the zlib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems

BUILD FAILED
```

Eventually I found this post that gave me some info further. I read through it and a few other pages and it seemed to me that the OpenSSL from brew was not working with this version of python.

[https://github.com/pyenv/pyenv/issues/1669](https://github.com/pyenv/pyenv/issues/1669)

This post references this command

```bash
PYTHON_BUILD_HOMEBREW_OPENSSL_FORMULA=openssl@1.0 pyenv install 2.6.9
```

This appeared to work for the guy. Alas it did not work for me on that version or 2.7.9. So I screwed around with a few commands a bit more and nothing seemed to work. EVENTUALLY, I aged 400 years and I had some nicotine I was able to clear a bit of how clouded my head was from anger and frustration and I looked at the output from that command and the complaints about OpenSSL from the line that worked on 3.8.0. So what I ended up doing was stripping some commands from the previously mentioned command to install 3.8.0. I got rid of all info surrounds ssl in that command and ended up just defining my CFLAGS and LFLAGS as such

```bash
CFLAGS="-I$(brew --prefix bzip2)/include -I$(brew --prefix readline)/include -I$(xcrun --show-sdk-path)/usr/include -I/usr/local/opt/sqlite/include" 
LDFLAGS="-L$(brew --prefix readline)/lib -L$(brew --prefix zlib)/lib -L$(brew --prefix bzip2)/lib -L/usr/local/opt/sqlite/lib"
```

Notice the stuff around ssl gone. Now with these flags set this way executed

```bash
PYTHON_BUILD_HOMEBREW_OPENSSL_FORMULA=openssl@1.0 pyenv install 2.7.9
```

The following I was so exhausted from rage I couldn't even celebrate. My whole world was shaken because I had no great battles left to fight. My purpose was over.

```bash
mac256g:~ doctorduke$ PYTHON_BUILD_HOMEBREW_OPENSSL_FORMULA=openssl@1.0 pyenv install 2.7.9
Error: No available formula with the name "openssl@1.0".
Downloading openssl-1.0.2k.tar.gz...
-> https://pyenv.github.io/pythons/6b3977c61f2aedf0f96367dcfb5c6e578cf37e7b8d913b4ecb6643c3cb88d8c0
Installing openssl-1.0.2k...
Installed openssl-1.0.2k to /Users/doctorduke/.pyenv/versions/2.7.9

python-build: use readline from homebrew
Downloading Python-2.7.9.tar.xz...
-> https://www.python.org/ftp/python/2.7.9/Python-2.7.9.tar.xz
Installing Python-2.7.9...
patching file ./Lib/site.py
patching file ./Lib/ssl.py
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
Installed Python-2.7.9 to /Users/doctorduke/.pyenv/versions/2.7.9
```

I now have no idea what to do. I guess I could catch up on the classes I had scheduled for the day but had to skip. Maybe I could take another step toward playing with Home Assistant. If you can call over 8 hours of wanting to drive a knife through your temple "playing". At this point I'm afraid of snakes and worried if I even try to run some python it will give me an error and I'll have to throw myself off the roof.

Any way. I hope you enjoyed my dark humour around a frustrating issue and my apparent incompetence. If I know engineers on the internet I'll hear some less than polite words about my stupidity either directly or indirectly. But I just really hope I can spare someone the frustration and stolen time so they can take their classes.

### Few things at the end I can't remember the details of.

I'm just going to throw this at the end but this was what I was originally trying to do and at some point something complained about this and I followed the steps on this page [https://github.com/pyenv/pyenv-virtualenv/issues/25](https://github.com/pyenv/pyenv-virtualenv/issues/25) to get around it. Blanking on where that happened. If you encounter it and I can update this post let me know.

```bash
brew install --HEAD pyenv-virtualenv
```

Let me just keep reminding you, when everything is inexplicably failing sometimes you have to go slightly braindead and just follow the instructions to find your way back. So I know some of these steps are "Duh." "Idiot doesn't know." "Amateur." But EVERY STEP WAS A PAIN and even the resolution steps were unclear or only worked in some cases. 

### Close

If there are edits to this process let me know. I'm not one that normally posts things out there for people to see because typically you're just inviting a chance to get insulted by someone smarter than you at working with these things but not smart enough to realize some people just don't encounter these situations and some people make mistakes and overlook things. Most of the time this stuff is put out the current fire and deal with the next fire when it occurs and I'm currently in a place where I'm trying to get all the fires out of the way so I can be better informed so when the next fire happens it's not quite as big. If you experience some variations because of a changed Mac OS version or different pyenv or Homebrew or if you just want to say hi, let me know. I'll try and update this post whereever I end up putting it or I'll say hi back. If you come across better versions of the errors or more informative ones than I included I'll do that too. If you have the inkling to help make it easier for others down the road. Also please keep in mind everyone starts somewhere and again, some kid could be playing with his first computer he just got and wants to play with Python to learn something having never used a single tool and he could encounter this. So many steps out there tell you what one versions solution was but a that kid's setup may not work with that version. I don't know, that's just how I look at it.

Oh man! I almost forgot. If you know how to fix Chrome always launching new windows in the top left when you want it in the bottom right corner GOD please let me know. It's killing me. My monitor is a 55 inch tv so that I can treat it like 4 screens to have reference stuff up and it drives me nuts!!

**Comment by mcandre** [comment]
This problem is worsened by the pyenv build process identifying the OpenSSL version belatedly, partway into the compilation instead of at the very beginning.

Each debug iteration takes several minutes to fail, so the user has little information to work with.

**Comment by native-api** [comment]
Summary of possible reasons and solutions is at https://github.com/pyenv/pyenv/wiki/Common-build-problems#error-the-python-ssl-extension-was-not-compiled-missing-the-openssl-lib

**Comment by bradley** [comment]
This is pretty over the top but what finally ended up working for me (M1), but I ended up adding this to my `.zshrc`. It does alias's calls to `pydev` to add various apparently necessary configurations, and only does so in instances where the developer (me) is running an `pydev install`. It will log a colorful warning message in such cases so that I dont forget this is happening or where to look if something starts to bug later:

```zsh
# Standard pyenv stuff
export PATH=/usr/local/bin:$PATH
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# The pyenv alias function
function bradley_pyenv {
    if [[ $1 == "install" ]]; then
        print -P  "%F{cyan}Executing 'pyenv' as alias to 'bradley_pyenv'. See .zshrc for details!%f"

        # The following section configures various flags necessary to get pyenv
        # working with our OS. Please update as any of these details change, e.g.;
        # the OSX version or deployment target.

        # about readline
        export LDFLAGS="-L$(brew --prefix readline)/lib $LDFLAGS"
        export CPPFLAGS="-I$(brew --prefix readline)/include $CPPFLAGS"
        export CFLAGS="-I$(brew --prefix readline)/include $CFLAGS"
        # about openssl
        export LDFLAGS="-L$(brew --prefix openssl)/lib $LDFLAGS"
        export CPPFLAGS="-I$(brew --prefix openssl)/include $CPPFLAGS"
        export CFLAGS="-I$(brew --prefix openssl)/include $CFLAGS"
        # about tcl-tk
        export LDFLAGS="-L$(brew --prefix tcl-tk)/lib $LDFLAGS"
        export CPPFLAGS="-I$(brew --prefix tcl-tk)/include $CPPFLAGS"
        export CFLAGS="-I$(brew --prefix tcl-tk)/include $CFLAGS"
        # about zlib
        export LDFLAGS="-L$(brew --prefix zlib)/lib $LDFLAGS"
        export CPPFLAGS="-I$(brew --prefix zlib)/include $CPPFLAGS"
        export CFLAGS="-I$(brew --prefix zlib)/include $CFLAGS"
        # about bzip2
        export LDFLAGS="-L$(brew --prefix bzip2)/lib $LDFLAGS"
        export CPPFLAGS="-I$(brew --prefix bzip2)/include $CPPFLAGS"
        export CFLAGS="-I$(brew --prefix bzip2)/include $CFLAGS"
        # about sqlite3
        export LDFLAGS="-L$(brew --prefix sqlite3)/lib $LDFLAGS"
        export CPPFLAGS="-I$(brew --prefix sqlite3)/include $CPPFLAGS"
        export CFLAGS="-I$(brew --prefix sqlite3)/include $CFLAGS"

        export CFLAGS="-I$(xcrun --show-sdk-path)/usr/include"

        export SDKROOT="$(xcrun --show-sdk-path)"

        export MACOSX_DEPLOYMENT_TARGET=13.3

        export PYTHON_BUILD_HOMEBREW_OPENSSL_FORMULA="openssl@3"

        export PYTHON_CONFIGURE_OPTS=--enable-unicode=ucs2

        export CC="$(brew --prefix gcc)/bin/gcc-13"

        # Execute custom pyenv command...
        command arch -x86_64 pyenv "$@"
    else
        # Execute as normal...
        command pyenv "$@"
    fi
}

alias pyenv=bradley_pyenv
```
